spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true      # fetch registry server and register's
    service-url:
      defaultZone: http://localhost:8761/eureka     #it uses this url to register with server
